site_name: HMC Makerspace
theme_dir: cinder
pages:
- Home: index.md
- Resources:
    - Tools: resources/tools.md
    - Supplies: resources/supplies.md
    - Projects: resources/project.md
    - Software: resources/software.md
    - Mentors: resources/mentor.md
- Policies: policies.md
- Tutorials: tutorials.md
- Project Showcase: showcase.md
- 'hidden': project-files/2017-fall/wok/wok_description.md
- 'hidden': project-files/2018-spring/cute-compute-cluster/ccc.md
- 'hidden': project-files/2018-spring/copperplating/copper-electroplating.md
    
